### ISSUE TITLE
Incompatible with ResourcefulBees; permanently breaks centrifuge recipes

### ISSUE THREAD

**Issue by tlitookilakin** [PORTB/PrecisionMining#5]
**Version:**
forge 36.1.0
precision mining 2.4
resourceful bees 0.6.7.2b

**Bug:**
Whenever a world is created while precision mining is installed, all centrifuge recipes are invalidated and will not process. This effect persists on these worlds even when precision mining is uninstalled. Conversely, worlds created _without_ precision mining continue to have working centrifuge recipes after precision mining is installed.

**To Reproduce:**
1. Install precision mining and resourceful bees together
2. create a new world with any settings
3. attempt to centrifuge any honeycomb, including the vanilla honeycomb, in any centrifuge.

**Comment by PORTB** [comment]
While I can reproduce it in production, it works fine in a resourcefulbees dev environment. Additionally, I can't figure out how to get resourcefulbees to compile to a jar that works at runtime (I keep getting "NoClassDefFoundError: ItemLike") so I'm not sure if it's just the dev env being different or something was changed. 

In other words, I have no idea how to solve this, I have no idea how this mod is even causing that, I'm not even touching recipes.

**Comment by tlitookilakin** [comment]
I don't know either, but it only happens when this mod is installed. I'm sorry I can't be of more help here.
I haven't tried with a dev environment, so there may be a difference between the dev and compiled versions.
Are you able to replicate it outside of a dev environment?

**Comment by PORTB** [comment]
I could replicate it outside dev environment.
I could also replicate it inside dev environment today, and I have no idea why.
Unfortunately I am not going to have time to understand how on earth this is happening due to school.

**Comment by PORTB** [comment]
oops

**Comment by tlitookilakin** [comment]
Thanks for looking into it :)

**Comment by PORTB** [comment]
Fixed. The problem was one of the functions I was using in the **TOOLTIP**
